// Generated by scripts/download-mushroom-photos.mjs — do not edit by hand.
// Photos: iNaturalist observers, CC0 / CC BY / CC BY-SA. See scripts/mushroom-photos.json.
import type { MushroomImage } from './mushroomImageTypes';

export const MUSHROOM_IMAGES: Record<string, MushroomImage[]> = {};
